### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by RSamaium** [sylvainbizeau/Compteur#2]
J'ai codé ton idée

https://transfer.sh/oTVxr/compteur.zip

1. Faire `npm install` à la racine 
2. Faire `npm run dev` pour tester

PS: Je n'ai pas mis l'incrémentation, à toi de l'intégrer

**Comment by sylvainbizeau** [comment]
je viens de faire la MAJ.
je n'ai plus de pb CORS mais j'ai encore qlq pb en local. je t'en dirais plus si je sèche
